<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="X7026772" name="Jenkins integration" tests="3" failures="1" timestamp="20 Dec 2019 20:24:38 GMT" time="8.932" errors="0">
  <testcase name="getData" time="0.011" classname="Jenkins_new_Java.testing">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.fail(Assert.java:56)
	at Jenkins_new_Java.testing.getData(testing.java:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getData -->
  <testcase name="login1" time="7.57" classname="Jenkins_new_Java.testing"/>
  <testcase name="success" time="0.0" classname="Jenkins_new_Java.testing"/>
</testsuite> <!-- Jenkins integration -->
